name: Build and push

on: ['push']


env:
  REPO: setecrs/iped_jobs
  FOLDER: .
  VERSION: ${GITHUB_REF#refs/tags/}

jobs:
  bare-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - run: python3 -m pip install -r requirements.txt
        working-directory: ./${{env.FOLDER}}

      - run: python3 -m unittest -v
        working-directory: ./${{env.FOLDER}}

  push:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - bare-unit-tests
    steps:
      - uses: actions/checkout@v2

      - name: pull latest (for cache)
        run: docker pull ${{env.REPO}}:latest || echo could not pull

      - name: Docker build latest
        run: docker build --cache-from ${{env.REPO}}:latest ${{env.FOLDER}} -t ${{env.REPO}}:latest
        
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        
      - name: Docker push latest
        run: docker push ${{env.REPO}}:latest
        
      - name: Docker push - semver
        run: |
          docker tag ${{env.REPO}}:latest ${{env.REPO}}:${{env.VERSION}}
          docker push ${{env.REPO}}:${{env.VERSION}}

